[package]
name = "wasm_syntax_gen"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
leb128 = "0.2.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "fold", "full", "visit"] }
